instantsoft/icms2

system/core/template.php, templates/default/assets/ui/menu.tpl.php
Добавлена поддержка html5 data атрибутов при добавлении кнопок меню.
=> Добавлена поддержка html5 data атрибутов при добавлении кнопок меню.

system/core/formfield.php, system/fields/listgroups.php, templates/default/assets/fields/listgroups.tpl.php
Просто как вариант без изменения логики cmsFormField
=> Вынос кода из шаблонов полей

system/fields/date.php, system/languages/en/language.php, system/languages/ru/language.php, templates/default/assets/fields/checkbox.tpl.php, templates/default/assets/fields/date.tpl.php
Когда нужно просто много чекбоксов, например в строках таблиц, labеl мешается
=> Убрать label без title

system/core/config.php
При установке постоянно попадаю на три ошибки, надо устранить недоразумение. По предупреждению остановился на сообщении, хотя можно и 404 показать.
=> ловим ошибку при отсутствии файла конфигурации

system/controllers/admin/actions/content.php, system/controllers/admin/actions/content_items_ajax.php, system/controllers/users/model.php, system/core/controller.php, system/core/template.php, system/core/user.php, templates/default/assets/ui/grid-data.tpl.php, templates/default/controllers/admin/content.tpl.php, templates/default/js/datagrid.js
=> Revert "User Personal Settings, баги в гриде, заголовки для гридов"

system/core/mailer.php
Происходит захват всех символов  до конца списка $letter_text. Соответственно в массив попадает одна не корректная ссылка на файл.
=> Не отправляет более одного вложений

system/controllers/tags/backend/actions/edit.php
Если тег не изменился, то ничего не трогаем и редиректим обратно.
=> Редактирование тегов в админке

system/controllers/content/actions/item_add.php, system/controllers/content/actions/item_edit.php, templates/default/assets/fields/date.tpl.php
При редактировании опубликованной сегодня записи она скрывается
=> Момент публикации в секундах, а не днях

system/controllers/admin/actions/settings_scheduler_toggle.php, system/controllers/admin/grids/grid_scheduler.php, system/controllers/admin/model.php
Можно не заходя в само задание, отключать или включать его. Нужно кликнуть по галочке в столбце активность, напротив самого задания.
=> Управление активностью заданий планировщика по ajax

templates/default/css/theme-widgets.css
Доработал стили для слайдера контента, исправил ошибки проявлявшиеся на мобильных устройствах.
=> Поправки стилей слайдера контента

templates/default/assets/ui/filter-panel.tpl.php, templates/default/css/theme-gui.css
Можно заменить слово на "Свернуть" или заменить картинкой.
=> Кнопка "Закрыть" для панели фильтра

templates/default/admin.tpl.php, templates/default/assets/errors/notfound.tpl.php, templates/default/assets/errors/offline.tpl.php
Заменяем $this->name на default в шаблоне default
=> Заменяем $this->name на default в шаблоне default

templates/default/controllers/content/category_view.tpl.php
Добавляет возможность присваивания класса тегу li списка категорий.
Для предоставления возможности в стилях индивидуализировать изображения категорий.
=> Свои стили для списка категорий

system/controllers/activity/hooks/publish_delayed_content.php, system/controllers/activity/manifest.php
https://github.com/instantsoft/icms2/issues/177
=> Добавление записи в ленту

system/core/core.php
Загружаем .tpl шаблоны виджетов из default, если их нет в текущем шаблоне
=> Загружаем .tpl виджетов из default

system/libs/template.helper.php
Устанавливаем минимальную яркость цвета фона аватара, и снижаем прозрачность, т.е. увеличиваем непрозрачность, чтобы результат был более насыщенным и жизнерадостным
=> Небольшая доработка генерируемых аватарок

templates/default/css/theme-gui.css
=> Небольшая доработка генерируемых аватарок (css)

system/controllers/admin/model.php
В логе получал ошибки на эту строку
=> Проверка массива перед циклом

system/controllers/comments/actions/rate.php
Запятая в место точки, из за этого не добавляется запись в ленту активности
=> Маленький баг

system/controllers/activity/widgets/list/widget.php
В файле \system\controllers\activity\frontend.php в строке 100 есть хук для обработки страницы самой Активности, но нет для виджета
=> Хук для обработки виджета Активность

system/controllers/admin/actions/cache_delete.php, system/controllers/admin/forms/form_settings.php, system/languages/en/controllers/admin/admin.php, system/languages/ru/controllers/admin/admin.php, templates/default/controllers/admin/styles.css, templates/default/main.tpl.php
https://github.com/instantsoft/icms2/issues/197
=> Быстрая очистка кэша

system/controllers/photos/actions/upload.php
В логе сервера получал ошибки
PHP Notice:  Undefined index: quality in \system\controllers\photos\actions\upload.php on line 154
Добавил качество по умолчанию, ошибка пропала
=> Качество фото по умолчанию

system/languages/en/language.php, system/languages/ru/language.php, templates/default/assets/errors/notfound.tpl.php, templates/default/css/theme-errors.css
Обновил 404 страницу и внес попутно необходимые изменения. Выглядит как тут. [http://cssdeck.com/labs/lulwvxke](http://cssdeck.com/labs/lulwvxke)
=> На страницу 404 добавлена форма поиска

system/controllers/content/model.php, system/controllers/users/actions/profile_content.php
При отключение у всех типов контента вывода списка в профиле, блок для списка продолжает выводиться (две параллельные линии по горизонтали).
=> Список контента в профиле

system/fields/list.php, system/languages/en/language.php, system/languages/ru/language.php, templates/default/assets/fields/list.tpl.php
Для поля список с мультивыбором предлагать не просто "Выбрать", а
"Выбрать  несколько".
=> Выбрать несколько

templates/default/js/images-upload.js
Переменная result не существует, из за этого получаем ошибку, когда обращаемся к removeCallback
=> Несуществующая переменная

templates/default/js/core.js
Решение этой проблемы https://github.com/instantsoft/icms2/issues/583
=> Проверка на существование #breadcrumbs

system/controllers/moderation/actions/index.php
При переходе по ссылкам пагинатора, была 404 ошибка.
=> Недочет пагинатора

templates/default/js/datagrid.js
=> #687 Add quotes into selectors (filter and order) in datagrid.js

templates/default/controllers/content/category_view.tpl.php
Убирает из ссылки на общую ленту RSS (в корневой категории) лишние параметры
=> Корректировка ссылки на ленту RSS

system/controllers/content/frontend.php
Хук для обработки данных полей перед формированием мета-тегов при сохранении записи.
=> Хук "prepare_item_seo"

system/controllers/admin/actions/controllers_delete.php
В модели уже осуществляется преобразование в массив
https://github.com/instantsoft/icms2/blob/master/system/controllers/admin/model.php#L32
=> После удаления не отображается список файлов

templates/default/js/core.js
Здравствуйте, можно в core.js добавить эту строку? icms.events.run('icms_tab_cliked', this);
Некоторые скрипты не инициализируются, когда их не видно, поэтому нужна событие, которая сообщить что был переход по вкладкам.
=> Событие на смену таба

system/controllers/admin/forms/form_ctypes_field.php, system/controllers/content/frontend.php, system/controllers/groups/actions/group.php, system/controllers/groups/actions/group_closed.php, system/controllers/groups/backend/forms/form_field.php, system/controllers/groups/frontend.php, system/controllers/users/actions/profile_edit.php, system/controllers/users/backend/forms/form_field.php, system/languages/en/controllers/admin/admin.php, system/languages/ru/controllers/admin/admin.php, templates/default/content/default_item.tpl.php, templates/default/controllers/users/profile_view.tpl.php
Доступ на чтение и изменение поля для автора записи или владельца группы/профиля.
=> Доступ для автора или владельца

system/controllers/admin/actions/content_grid_columns.php, system/controllers/admin/actions/content_items_ajax.php, system/controllers/admin/actions/ctypes_field_string_ajax.php, system/controllers/admin/actions/toggle_item.php, system/controllers/admin/backend.php, system/controllers/admin/frontend.php, system/controllers/admin/grids/grid_content_items.php, system/controllers/admin/hooks/grid_admin_content_items_args.php, system/controllers/admin/manifest.php, system/core/controller.php, system/core/formfield.php, system/core/template.php, system/fields/string.php, system/languages/en/controllers/admin/admin.php, system/languages/en/language.php, system/languages/ru/controllers/admin/admin.php, system/languages/ru/language.php, system/libs/strings.helper.php, system/libs/template.helper.php, templates/default/assets/fields/string.tpl.php, templates/default/assets/ui/filter-panel.tpl.php, templates/default/controllers/admin/content.tpl.php, templates/default/controllers/admin/content_grid_columns.tpl.php, templates/default/controllers/admin/styles.css, templates/default/js/admin-content.js, templates/default/js/datagrid.js, templates/default/js/fields/string.js
Баг с z-index календаря в гриде
Баг с выделением пустой строки в гриде
Отображение направления сортировки при первой загрузке грида
Настройка строкового поля в фильтре
=> Настраиваемые столбцы в гридах контента

system/controllers/admin/actions/widgets_add.php, system/controllers/admin/actions/widgets_copy.php, system/controllers/admin/actions/widgets_delete.php, system/controllers/admin/actions/widgets_edit.php, system/controllers/admin/actions/widgets_reorder.php, system/controllers/admin/actions/widgets_toggle.php, system/controllers/admin/actions/widgets_update.php, system/controllers/admin/frontend.php, system/controllers/content/widgets/categories/widget.php, system/controllers/widgets/model.php, system/languages/en/controllers/admin/admin.php, system/languages/ru/controllers/admin/admin.php, templates/default/controllers/admin/styles.css, templates/default/controllers/admin/widgets.tpl.php, templates/default/js/admin-widgets.js
Баг виджета категорий, работа даже в момент, когда категории отключены
=> Привязка виджетов к нескольким страницам

system/core/template.php, templates/default/controllers/content/item_form.tpl.php, templates/default/main.tpl.php, wysiwyg/redactor/files/redactor.js
Подключение системных необходимых скриптов в форме редактирования итема,
size() на length в редакторе для поддержки современной jquery
=> Возможность помещать скрипт в самое начало

system/controllers/admin/hooks/grid_admin_content_items_args.php, system/fields/number.php, system/languages/en/language.php, system/languages/ru/language.php
Место для спецсимвола в качестве разделителя
Баг при смене алиаса поля
=>  Разделитель для единиц измерения 

templates/default/controllers/users/profile_view.tpl.php
Блок после аватара, что бы без правки код шаблона можно было вывести различные улучшения по аватару.
=> Блок после аватара

templates/default/controllers/users/profile_view.tpl.php
Что бы добавить в профиль пользователя такие блоки как, Блок друзей или контента (то что сейчас есть)
=> Вывод своих div блоков

system/controllers/menu/model.php
=> Не выводить в меню пункты

templates/default/controllers/activity/backend/admin_dashboard_block_activity.tpl.php
После очистки ленты, в блоке выводится ошибка:  Invalid argument supplied for foreach() in
=> При пустой ленте ошибка

system/core/form.php
Приоритет методов валидации:
- в классе формы
- в классе поля
- в контроллере
=> cmsForm: Добавлена возможность переопределения методов валидации в классе формы

system/core/database.php
в метод insert добавлен параметр $ignore
=> cmsDatabase: добавлена поддержка запроса INSERT IGNORE

templates/default/js/fields/string_input.js
В ui храниться все данные по выбранному пункту id, label, value
=> Замена this на ui

install/languages/en/base.sql, install/languages/en/base_demo_content.sql, install/languages/ru/base.sql, install/languages/ru/geo.sql, install/steps/database.php, system/controllers/content/actions/category_view.php, system/controllers/content/actions/item_view.php, system/controllers/geo/backend/grids/grid_cities.php, system/controllers/geo/backend/grids/grid_countries.php, system/controllers/geo/backend/grids/grid_regions.php, system/controllers/geo/model.php, system/core/controller.php, system/fields/color.php, system/languages/en/language.php, system/languages/ru/language.php, templates/default/assets/fields/color.tpl.php, templates/default/profiles/options.form.php, update/current/install.php
https://github.com/instantsoft/icms2/issues/605
https://github.com/instantsoft/icms2/issues/492
https://github.com/instantsoft/icms2/issues/695
=> Закрытие нескольких Issues

system/controllers/groups/frontend.php
Добавляем проверку на включенность лента активности, так как если выключен, в группах работает лента
=> Проверка на включенность ленты

system/controllers/groups/frontend.php
Исключаем возможность зайти на страницу группы символами разного регистра
=> Редирект на страницу группы согласно slug

system/controllers/admin/actions/content_cats_order.php, system/controllers/admin/actions/controllers_edit.php, system/controllers/admin/actions/users.php, system/controllers/content/actions/category_delete.php, system/controllers/menu/model.php, system/controllers/messages/model.php, system/controllers/users/actions/profile_invites.php, system/core/controller.php, system/core/core.php, system/core/database.php, system/core/form.php, system/core/template.php, system/libs/idna_convert.class.php, templates/default/assets/ui/breadcrumbs.tpl.php, templates/default/assets/ui/filter-panel.tpl.php, templates/default/assets/ui/grid-data.tpl.php, templates/default/controllers/content/widgets/filter/filter.tpl.php, templates/default/controllers/wall/entry.tpl.php, templates/default/controllers/wall/list.tpl.php, templates/modern/assets/ui/filter-panel.tpl.php, templates/modern/controllers/content/widgets/filter/filter.tpl.php, templates/modern/controllers/wall/entry.tpl.php, templates/modern/controllers/wall/list.tpl.php
'`sizeof(...)`' is an alias function, consider using '`count(...)`' instead.
=> Is an alias function

system/controllers/admin/actions/content_items_edit.php
В поля в админке при редактировании записи типа контента теперь передается больше информации
=> Массовое редактирование записей в админке

templates/modern/controllers/forms/index.tpl.php
Без этой правки js файл не подгружается в модальных окнах, в связи с чем после отправки формы js падает с ошибкой
=> Работа форм конструктора в модальных окнах

system/controllers/users/actions/profile_edit_password.php
Добавлен хук users_after_edit_password
=> Хук на обновление пароля

system/controllers/admin/actions/content_items_edit.php
Устраняем очистку дополнительных категорий при массовом изменении значения поля.
https://github.com/instantsoft/icms2/issues/1468#issue-1771144466
=> Сохраняем "Дополнительные категории"
