- system/controllers/tags/model.php
При редактировании записи и последующем вызове метода updateTags(...) удаляются связи с тегами в таблице {cms}_bind_tags но сами теги остаются в таблице {cms}_tags.
> Не очищаются "старые" теги

- templates/default/controllers/content/category_form.tpl.php
При добавлении или редактировании категории типа контента не выводится title страницы в зависимости от выполняемого действия.
> При добавлении или редактировании категории не отображается Title страницы

- system/controllers/tags/model.php
- system/core/database.php
Я как-то говорил **r2** об этой "баге", но решил сюда тоже добавить...
При удалении одной из записей с тегом (или несколькими тегами), который содержится еще в других записях, этот тег полностью удаляется из таблицы **{#}_tags**, и соответственно из всех остальных записей! Дополнительная фильтрация решает данную проблему.
> Удаляются теги из всех записей

- templates/.htaccess
При подключении гугл шрифта, один из форматов шрифта предоставляемый им это woff2, так же он более оптимизирован, предлогаю включить его в список разрешенных форматов файлов.
> Поддержка формата шрифта woff2

- system/core/template.php
Загружаем стили типов контента из папки /templates/default/content/ если их нет в текущем шаблоне...
Если есть, объединяем два массива и удаляем дубли...
> Загружаем стили из default, если их нет в шаблоне

- system/controllers/rss/backend/forms/form_feed.php
Если в основном шаблоне нет стили для rss, то возникают ошибка 503 Service Unavailable
> Загружаем стили rss из default, если их нет в шаблоне

- system/libs/strings.helper.php
Достаточно часто необходимо устанавливать одинаковые значения ключа ($key) и значения ($value) для выборки элементов из массива.
Изменения позволяют сократить код до следующего:
`$ids = array_collection_to_list($array, 'id');`
> Удобно выбирать ID из массивов

- system/core/mailer.php
При отправлении сложного HTML-письма, с тегами <style>, всё их наполнение оказывается внутри текстовой версии, наряду с чистым текстом письма из-за использования strip_tags.
Предлагаю воспользоваться готовым инструментом PHPMailer, который с чисткой HTML-письма справляется лучше :)
> Исправление конвертации HTML-письма в TXT-вариант

- system/core/form.php
Возникла необходимость взаимодействия с полями форм у дополнения iForms. iForms использует системные механизмы для формирования форм. 
Из группы полей получить конкретное нельзя, только перебором элементов. Предлагаю добавлять поле в группу полей с ключем - именем этого поля. 
Это не изменит работу CMS никаким образом, но в будущем даст возможность удобнее взаимодействовать с полями как контента, так и форм.
> В массив с полями формы добавляем поля с ключами-именами.

- system/core/backend.php
В ряде случаев есть необходимость выносить часть параметров из формы опций на другие формы админки компонента с последующим сохранением их через 
```
$options = cmsController::loadOptions($this->controller->name);
// здесь добавляем новых опций
cmsController::saveOptions($this->controller->name, $options);
```
При этом если внести изменения и нажать кнопку сабмита на стандартной форме опций, все ранее сохранённые параметры будут утеряны.
Commit добавляет пересохранение только массива стандартных опций не трогая параметры из других форм.
> Сохранение всех опций контроллера

- system/controllers/groups/actions/add.php
При создании группы не зависимо от параметра 'Показывать стену пользователя' выводился список настроек 'Кто может писать на стене группы'. Исправлено.
> Исправление работы параметра 'Показывать стену пользователя'

- system/core/controller.php
- system/core/core.php
Они всё равно не могут загрузиться через autoload и подключаются отдельно в специальных функциях.
> Убираем попытки автозагрузки классов моделей, контроллеров и хуков.

- system/controllers/admin/actions/install.php
Проверка версий функцией version_compare. 
То что было давала ошибку например при случае когда пакет обновлялся с версии 1.1.9 на 1.1.10 сообщая что 1.1.10 меньше чем 1.1.9
> Проверка версий функцией version_compare

- system/controllers/comments/frontend.php
Если у типа контента 2 модератора, то при получении комментарии на модерацию, уведомление дублируется
> Очистка списка получателей в цикле

- system/core/template.php
Здравствуйте, если включена Объединять CSS, при подключении CSS файла, где указана версия, например:
$this->addCSS('ПУТЬ_К_ФАЙЛУ/style.css?ver=1.0.0');
Получаем ошибку 
Warning: file_get_contents(ПУТЬ_К_ФАЙЛУ/style.css?ver=1.0.0) [function.file-get-contents]: failed to open stream: No such file or directory in \system\core\template.php on line 897
> Проблемы при Объединении CSS, когда указана версия

- system/controllers/users/actions/profile_edit.php
Исправление мелкого бага в ленте активности. При добавлении аватарки не используются заданный в опциях профиля пресет, а берётся просто "normal".
> Правильный пресет для большой аватарки в ленте активности

- system/controllers/content/actions/item_edit.php
Когда переменная читается в начале скрипта, то сторонние модули не имеют возможности её изменить через хуки, а если её читать после хуков, то можно через request->set изменить.
> получение back_url после хуков

- templates/default/js/core.js
Когда система создает select версию вкладок, в качестве опции берет все "ul > li > a" которые есть в блоке .tabs-menu, а надо что бы брал только первый ul, иначе в мобильных версиях в select отображается ссылки, которые есть внутри вкладок, где родитель ul > li
> Не правильно отображает вкладки в select

- system/core/controller.php
Чтобы убрать дублирующийся код и иметь возможность переопределения пути хранения файлов экшенов в контроллерах компонентов
> cmsController: Определение пути к экшену вынесено в отдельный метод getExternalActionPath

- templates/default/js/core.js
(select отображается в мобильном виде вместо табов)
сравнивалось по ссылке (видимо код был скопирован с аналогичной функции для меню на 59 строке того же файла)
исправлено на проверку наличия класса active у род.тега li
> Исправлено: установка активного элемента select'a списка табов

- system/controllers/admin/frontend.php
- system/core/controller.php
чтобы убрать дублирование кода и иметь возможность отключать или переопределять эту проверку в собственных модулях. Проверка была отключена для модуля admin, так что там этот метод переопределен.
> cmsController: Проверка на кол-во параметров при запуске action'а вынесена в метод validateParamsCount

- system/controllers/admin/actions/widgets_load.php
На странице site.ru/admin/widgets при выборе страниц сторонних компонентов (например форум) появляется предупреждение, которое блокирует работу яваскрипта по загрузке виджетов этой страницы.
PHP Warning:  constant() [<a href='0function.constant0'>function.constant0</a>]: Couldn't find constant LANG_WP_FORUM_MAIN_PAGE in system\controllers\widgets\model.php on line 275
> Недоступны языковые константы при загрузке виджетов

- system/fields/html.php
- system/languages/en/language.php
- system/languages/ru/language.php
Добавлены две опции в поле html для указания типа обрезки текста и символов, которые будут добавлены к полученной строке
> Более гибкая обрезка текста в поле html

- system/controllers/content/backend/model.php
В уже имеющемся хуке ctype_prop_after_update нет доступа к старому значению свойства
> Новый хук при редактировании свойств
